name: Validate CODEOWNERS
on:
  pull_request:
    branches: [test-codeowners-workflow]
jobs:
  checkIfCodeownersUpdateNeeded:
    permissions:
      pull-requests: write
    name: Check if CODEOWNERS needs to be updated
    runs-on: ubuntu-latest
    steps:
      - name: Get count of added files
        uses: actions/github-script@v6.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const script = require('./.github/workflows/scripts/check_for_new_files_script.js');
            script({github, context});
      - name: Checkout repository
        if: ${{ env.NEW_FILES_COUNT > 0 }}
        uses: actions/checkout@v3
      - name: Install npm package ignore
        if: ${{ env.NEW_FILES_COUNT > 0 }}
        run: yarn add ignore -W # help verify CODEOWNERS
      - name: Check file against CODEOWNERS
        if: ${{ env.NEW_FILES_COUNT > 0 }}
        uses: actions/github-script@v6.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ignore = require('ignore');
            const { validateCodeowners } = require('./.github/workflows/scripts/check_for_new_files_script.js');
            validateCodeowners({github, context, fetch, ignore});
