name: Lighthouse CI
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
env:
  BUILD_DIR: 'client/www/next-build'
  CONFIG_PATH: './.github/workflows/lighthouse_configs/performance.mjs'
jobs:
  lighthouse-performance:
    name: Runs lighthouse with the performance category
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: yarn
      - name: Run Build
        run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Get changed/new pages to run lighthouse performance audit on
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: pages-to-test-performance
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { getChangedPages } = require('./.github/workflows/scripts/check_for_changed_pages.js');
            const buildDir = process.env.BUILD_DIR;
            return getChangedPages({github, context, buildDir});
      - name: Run site
        run: |
          npx serve ${{ env.BUILD_DIR }} &
          sleep 5
      - name: Run Lighthouse performance audit
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { runPerformanceAudit } = require('./.github/workflows/scripts/run_performance_audit.js');
            const pages = ${{ steps.pages-to-test-performance.outputs.result }};
            return await runPerformanceAudit(pages);
      - name: Save Lighthouse reports to artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: lighthouse-performance-results
          path: LH_performance*.html
