name: Lighthouse CI
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
env:
  BUILD_DIR: 'client/www/next-build'
  CONFIG_PATH: './.github/workflows/lighthouse_configs/performance.mjs'
jobs:
  lighthouse-performance:
    name: Runs lighthouse with the performance category
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: yarn
      - name: Run Build
        run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Install lighthouse cli
        run: yarn global add lighthouse
      - name: Get changed/new pages to run lighthouse performance audit on
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: pages-to-test-performance
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { getChangedPages } = require('./.github/workflows/scripts/check_for_changed_pages.js');
            const buildDir = process.env.BUILD_DIR;
            return getChangedPages({github, context, buildDir});
      - name: Print pages
        run: echo "${{steps.pages-to-test-performance.outputs.result}}"
      - name: Run site
        run: | 
          python -m http.server 3000 -d ${{ env.BUILD_DIR }} &
          sleep 5
      - name: Run Lighthouse
        run: |
          lighthouse http://localhost:3000 --config-path=${{env.CONFIG_PATH}} --quiet --chrome-flags="--headless" --output json --output-path ./performance-run.json 
