name: Sync to S3
on:
  schedule:
    - cron: '0 17 * * 1-5'
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  SyncToS3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup Node.js 20
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: yarn
      - name: Run Build
        run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: arn:aws:iam::789362886327:role/docs_test_s3_sync_role
          aws-region: us-east-1
      - name: Remove unnecessary files
        run: |
          rm -rf ./client/www/next-build/_next
          rm -rf ./client/www/next-build/images
          rm -rf ./client/www/next-build/videos
          rm -rf ./client/www/next-build/assets
          rm -rf ./client/www/next-build/fonts
      - name: Sync build output
        run: | 
          aws s3 sync ./client/www/next-build s3://aws-amplify-docs-export-bucket --delete
      - name: Count files in S3 bucket
        run: echo "s3FileCount=$(aws s3 ls s3://aws-amplify-docs-export-bucket --recursive | wc -l)" >> $GITHUB_ENV
      - name: Count files in local directory
        run: echo "localFileCount=$(find ./client/www/next-build -type f | wc -l)" >> $GITHUB_ENV
      - name: Validate sync
        run: |
          if [ ${{ env.s3FileCount }} -eq ${{ env.localFileCount }} ]; then
            echo "File counts are equal"
          else
            echo "File counts are not equal"
            echo "S3 count: ${{ env.s3FileCount }}"
            echo "Local count: ${{ env.localFileCount }}"
            exit 1
          fi
