name: Verify Approvers
on:
  pull_request_review:
    types: [submitted]
jobs:
  verifyApproval:
    name: Verify approvals
    runs-on: ubuntu-latest
    steps:
      - name: Check if approver is from requested reviewers
        if: github.event.review.state == 'approved'
        uses: actions/github-script@v6.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context.payload.review);
            console.log(context.payload.review.state);
            console.log(context.payload.review.user.login);

            console.log(context.pull_request)

            //const { payload: { pull_request: issue_number }, repo: { owner, repo } } = context;

            //github.rest.pulls.listRequestedReviewers({''})
